# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .


# Stage 2: Production
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app ./
COPY package*.json ./
RUN npm ci --omit=dev
CMD ["node", "index.js"]

