version: '3.8'

services:
  app:
    image: srinathchitha/express-todo:v1
    container_name: todo-app
    restart: always
    depends_on:
      - mongo
      - redis
    ports:
      - "5050:5000"
    environment:
      PORT: ${PORT}
      MONGODB_URI : ${MONGODB_URI}
      MONGODB_DB : ${MONGODB_DB}
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
